/**
 * Rewrites the auto-generated `EXPECTED_CHANNELS` snapshot in
 * `apps/electron/src/shared/__tests__/ipc-channels.test.ts` from the live
 * `RPC_NAMESPACES`.
 *
 * The snapshot is a wire-format guard: renaming or dropping a channel string
 * breaks every already-installed client, so the diff has to be visible in
 * review rather than inferred. Regenerating it is mechanical, which is exactly
 * why it is a script and not a hand-edited list — the file's own header points
 * here, and hand-patching 400 sorted strings is how the list silently drifted
 * out of date before.
 *
 * Run after adding, removing or renaming any `RPC_NAMESPACES` entry:
 *   bun run scripts/ipc-inventory.ts
 */

import { readFileSync, writeFileSync } from 'fs'
import { join } from 'path'
import { RPC_NAMESPACES } from '../packages/shared/src/protocol/channels'

const TEST_FILE = join(
  import.meta.dir,
  '..',
  'apps',
  'electron',
  'src',
  'shared',
  '__tests__',
  'ipc-channels.test.ts',
)

const BEGIN = '// Auto-generated by scripts/ipc-inventory.ts — DO NOT edit by hand.'
const END = '// End auto-generated'

function flattenValues(obj: Record<string, unknown>): string[] {
  return Object.values(obj).flatMap((value) =>
    typeof value === 'string' ? [value]
      : typeof value === 'object' && value !== null ? flattenValues(value as Record<string, unknown>)
      : []
  )
}

const channels = flattenValues(RPC_NAMESPACES).sort()
const duplicates = channels.filter((channel, index) => channels[index - 1] === channel)
if (duplicates.length > 0) {
  // Two namespaces sharing a wire string route to one handler: refuse to bake
  // that into the snapshot, where it would then read as intentional.
  throw new Error(`Duplicate RPC channel strings: ${[...new Set(duplicates)].join(', ')}`)
}

const source = readFileSync(TEST_FILE, 'utf8')
const beginIndex = source.indexOf(BEGIN)
const endIndex = source.indexOf(END)
if (beginIndex === -1 || endIndex === -1 || endIndex < beginIndex) {
  throw new Error(`Could not find the generated block markers in ${TEST_FILE}`)
}

const block = [
  BEGIN,
  'const EXPECTED_CHANNELS: string[] = [',
  ...channels.map((channel) => `  ${JSON.stringify(channel)},`),
  ']',
  '',
  'const EXPECTED_COUNT = EXPECTED_CHANNELS.length',
  '',
].join('\n')

writeFileSync(TEST_FILE, source.slice(0, beginIndex) + block + source.slice(endIndex), 'utf8')
console.log(`ipc-inventory: wrote ${channels.length} channel(s) to ${TEST_FILE}`)
